config/routes.rb
Rails.application.routes.draw do
root "students#index"

resources :students
resources :subjects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :subjects 
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(radio_params)
     @student.save
     redirect_to  new_subject_path(id: @student.id)
  end
 private
 def radio_params
  params.require(:student).permit(:name)
 end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def new
    @subject = Subject.new
    
    @student = Student.find(params[:id])
  end

   def create
    @student = Student.find(params[:subject][:student_id])
    #debugger
    @subject = @student.subjects.build( many_params).save
    redirect_to student_path(@student.id)
  end

  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

 

  private
  def many_params
    params.require(:subject).permit(:branch, :student_id)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hasmany</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Welcome to my new page</h1>


<% @students.each do |a| %> 
  <%= link_to a.name, student_path(a.id) %><br> 
  <%= link_to "create branch",new_subject_path(id: a.id)%> <br><br>
 <% end %> 

<%= link_to "new page", new_student_path%>

app/views/students/new.html.erb
<h1> create</h1>

 <%= form_for @student do |form|%>
 <p>
  <%= form.label :Name %><br>
  <%= form.text_field :name %>
</p>

<p>
<%= form.submit "submit button" %>
</p>
<%end%>

app/views/students/show.html.erb
<h1>Show Page</h1>

Name: <%=@student.name %><br><br>
<%@student.subjects.each do |f|%>
<%= f.branch%><br>
<%end%><br><br>

 <br>

 <%= link_to 'create new' , new_student_path%>
 <%= link_to 'ORIGINAL PAGE' , students_path%>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>

app/views/subjects/new.html.erb
<h1>Subject</h1>

<%= form_for Subject.new do |form|%>

 <%= form.text_field :student_id, value: @student.id%>

 <p>
  <%= form.text_field :branch%>
</p>

<p>
  <%= form.submit "button"%>
</p>

<%end%>

app/views/subjects/show.html.erb
<h1>Subjects#show</h1>
<p>Find me in app/views/subjects/show.html.erb</p>